apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: api-demo
  labels:
    app.kubernetes.io/name: api-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: api-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-demo
    spec:
      containers:
        - name: api-demo
          image: ilmiont/tyk-gitops-demo:latest
          ports:
            - name: http
              containerPort: 3000
