apiVersion: v1
kind: Service
metadata:
  name: api-demo
  namespace: api-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
